new changes
Mash-Masha/studyWithBrother pull request #1
Opened 2020-12-09 11:15 UTC by Mash-Masha

2020-12-14 09:41 UTC, KirillKarpov approved these changes

2020-12-15 14:23 UTC, KirillKarpov approved these changes

2020-12-15 14:23 UTC, KirillKarpov commented on Task2
> +b.//div[@class='search-controls']/input[2]
Можно ещё //input[@name='search']

2020-12-15 14:23 UTC, KirillKarpov commented on Task2
> +e.//div[@class='b-auth-submit']/a
можно ещё //a[@class='button wide auth__reg']

2020-12-15 14:23 UTC, KirillKarpov commented on Task2
> +j.//span[@class='b-folders__folder__name']/a[not(@href='/lite/sent')]
или так //a[@class='b-folders__folder__link' and not(self::a[@href='/lite/sent'])]

2020-12-15 14:23 UTC, KirillKarpov commented on Task2
> +n.//button[contains(@class,'b-compose__more')]
ещё можно //button[@value='multy-att']

2020-12-15 14:23 UTC, KirillKarpov commented on Task2
> +o. //div[@class='b-buttons']/input[@type='submit']
или //div[@class='b-compose__more-attach']/following-sibling::input

2020-12-15 14:23 UTC, KirillKarpov commented on Task2
> +p.//input[@class='b-compose__file']/..//input
или //input[@class='b-compose__file']/following-sibling::input

2020-12-15 14:23 UTC, KirillKarpov commented on Task2
> +q.//button[@name='nosend']/../../input[@type='submit']
или //button[@name='nosend']/../following-sibling::input

2020-12-15 14:23 UTC, KirillKarpov commented on Task2
> +e.[class='b-auth-submit']>a
или a.button.wide.auth__reg

2020-12-15 14:23 UTC, KirillKarpov commented on Task2
> +g.a[class='b-header__link b-header__link_exit']
или a[href*='logout']

2020-12-15 14:23 UTC, KirillKarpov commented on Task2
> +j.span[class='b-folders__folder__name']>a:not([href='/lite/sent'])
или a.b-folders__folder__link:not([href*='/lite/sent'])

2020-12-15 14:23 UTC, KirillKarpov commented on Task2
> +l.#id1166527693078
или input[name=subj]

2020-12-15 14:23 UTC, KirillKarpov commented on Task2
> +n.button[name='nosend']
button[value=multy-att]

2020-12-15 14:23 UTC, KirillKarpov commented on Task2
> +s.//div[@class='b-buttons']/input[2]/following-sibling::input/preceding-sibling::input
или //div[@class='b-buttons']/input[@name!='doit']

2020-12-15 14:23 UTC, KirillKarpov commented on Task2
> +t.a[aria-label='4 FOURTH. 4 FOURTH'],a[aria-label='2 SECOND. 2 SECOND']
или div.b-messages__message:nth-of-type(2n+4)>span   >a.b-messages__message__link

Но именно это было со звездочкой

2020-12-15 14:23 UTC, KirillKarpov commented on Task2
> +u.
(//a[@class='b-messages__message__link'])[position()!=1]

2021-01-07 06:27 UTC, ghost commented on src/main/java/LoginLogoutTest.java
> +        driver.findElement(By.xpath("//div[@class='b-hold']/input[2]")).sendKeys("123456789zxcvbn");
старайся избегать xpath где есть обращения к какому-то числу input/div/a. В твоём случае это input[2]

2021-01-07 06:27 UTC, ghost commented on src/main/java/LoginLogoutTest.java
> +        WebElement button=driver.findElement(By.xpath("//div[@class='b-hold']//input[@value='Войти']"));
старайся по возможности не привязываться в локаторе к @value или text(). Это может стать проблемой, когда у тебя будет сайт на нескольких языках. Эти значения будут меняться

2021-01-07 06:27 UTC, ghost commented on src/main/java/task3pageobject/AlertMainPage.java
> +    }
Лишние методы лучше тоже не писать, чтобы не загромождать код. Думаю, что эти методы у тебя нигде не используются

2021-01-07 06:27 UTC, ghost commented on src/main/java/task3pageobject/AlertMainPage.java
> +    private By button2=By.xpath("//button[@onclick='myPromptFunction()']");
1)Переменные должны нести какой-то смысл, чтобы по названию было легко понять что это за переменная.
2) Плохим правилом считается создавать переменные с нумерацией как в твоём случае button1, button2
Как вариант можно назвать confirmButton, promptButton

2021-01-07 06:27 UTC, ghost commented on src/main/java/task3pageobject/AlertTest.java
> +        System.setProperty("webdriver.chrome.driver", "C:\\javalessons\\driver\\chromedriver.exe");
1) Путь не должен быть абсолютным и не должен быть привязан к твоей структуре папок. У меня chromedriver не лежит в C/javalesssons, так как у меня нет такой папке на компе. По этой причине этот тест не будет находить драйвер и будет падать.

2) Путь должен быть относительным. Драйвер лучше всего класть в папку resources.
Путь может выглядить вот так "./src/java/resources/drivers/chromedriver.exe"
3) Если используешь в имени пути \\ то такие тесты будут работать только на компьютерах где установлена Windows. Лучше использовать обратный слеш /. Такие тесты будут работать и на Linux и на Mac OS

2021-01-07 06:27 UTC, ghost commented on src/main/java/task3pageobject/AlertTest.java
> +            WebElement message=driver.findElement(By.xpath("//p[@id='confirm-demo']"));
У тебя есть alertMainPage. Почему ты обращаешься к вебэлементу на уровне теста? Почему не перенесла всю логику взаимодействия с алертом в класс alertMainPage ?

2021-01-07 06:27 UTC, ghost commented on src/main/java/task3pageobject/AlertTest.java
> +            Thread.sleep(3000);
Thread.sleep() надо было использовать во всех трёх тестах? Можешь обновить один тест и написать без статического ожидания?

2021-01-07 06:27 UTC, ghost commented on src/main/java/task3pageobject/LoginTest.java
> +        System.setProperty("webdriver.chrome.driver", "C:\\javalessons\\driver\\chromedriver.exe");
То же самое по поводу пути

2021-01-07 06:27 UTC, ghost commented on src/main/java/task3pageobject/LoginTest.java
> +        wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//span[text()='Selenium Test']")));
такого рода логику правильней всего спрятать на уровень страницы(MainPage ).
Каждый тест должен иметь проверку. Добавь пожалуйста в этом тесте

2021-01-07 06:27 UTC, ghost commented on src/main/java/task3pageobject/MainPage.java
> +    }
Геттеры и сеттеры лучше создавать по мере того как ты их используешь. Опять же чтобы не загромоджать класс кодом

2021-01-07 06:27 UTC, ghost commented on src/main/java/task3pageobject/MainPage.java
> +
Лишние пробелы :)

2021-01-07 06:27 UTC, ghost commented on src/main/java/task3pageobject/MainPageTest.java
> +    }
Это часть(как и AftreEach() )  у тебя повторяется в каждом тестов классе. 
Одна из главный задач это стараться избегать дубликации кода. 
Поэтому создай пожалуйста класс BaseTest, перенеси туда дублирующийся код и отнаследуй MainPageTest и другие тестовые классы от BaseTest

2021-01-07 06:27 UTC, ghost commented on src/main/java/task3pageobject/MainPage.java
> +    public SignInPage loginWithInvalidCreds(String login, String password) {
Почему метод называется withInvalidCreds ? А валидные данные можно в него передать ? :)

2021-01-07 06:27 UTC, ghost commented on src/main/java/task3pageobject/MultiSelectTest.java
> +            isSelectCalifornia.click();
1)Старайся всегда писать if конструкции со скобками. Это позволит видеть где начало и конец действия функции if
2) Старайся по возможности избегать конструкции if. Это усложняет логику теста и заставляет всегда продумывать секцию else(что мы ожидаем если if не отработал)
3) Если ты хотела проверить, что элемент не выбран,  в классе Select есть замечательный метод deselectAll()

2021-01-07 06:27 UTC, ghost commented on src/main/java/task3pageobject/MultiSelectTest.java
> +        WebElement isSelectCalifornia=driver.findElement(By.xpath("//option[text()='California']"));
isSelectCalifornia - если переменная начинается с is, то ожидается что это boolean переменная, когда должна возвращать true/false значение. В твоём случае это переменная класса  WebElement , поэтому лучше назвать её california

2021-01-07 06:27 UTC, ghost commented on src/main/java/task3pageobject/MultiSelectTest.java
> +    public void isSelectedRows() {
Если начинаешь название метода с is , то он не должен быть void. Принято чтобы у таких методов был возвращаемый объект типа boolean

2021-01-07 06:27 UTC, ghost commented on src/main/java/task3pageobject/MultiSelectTest2.java
> +    }
Задача этого задания была поработать с классом Select, который есть в библиотеке WebDriver. Напиши пожалуйста этот тест, но используя методы класса Select.
Select countiresDropDown = driver.findElements(By.xpath("//select[@id='multi-select']"));

2021-01-07 06:27 UTC, ghost commented on src/main/java/task3pageobject/RefreshTest.java
> +            actions.sendKeys(Keys.F5).build().perform();
тут воспользуйся пожалуйста ExpectedConditions.textMatches( By locator, Pattern pattern). 
А для обновления страницы воспользуйся методом из класса Navigation (подсказка: посмотри какие методы есть у driver)
Если будет сложно, то сильно не зависай и пиши мне

2021-01-07 06:27 UTC, ghost commented on src/main/java/task3pageobject/SignInPage.java
> +
А нужен ли тебе такой класс с одной переменной? 
Что-то мне кажется что этот локатор принадлежит классу MainPage

2021-01-07 06:27 UTC, KirillKarpov commented on src/main/java/task3pageobject/TablePage.java
> +
Лишние пробелы :)

2021-01-07 06:27 UTC, KirillKarpov commented on src/main/java/task3pageobject/TablePage.java
> +            String salary1=employee.findElement(By.xpath(".//td[6]")).getText();
лучше называть переменную tempSalary

2021-01-07 06:27 UTC, KirillKarpov commented on src/main/java/task3pageobject/TablePage.java
> +        allRows.remove(0);
Можно так. Но не очень хорошо. А что если вдруг завтра шапка(thead) будет состоять из двух или трёх строк ? :)
 А можно написать xpath , который будет возвращаться только строки из таблицы. driver.findElements(By.xpath(".//tbody//tr"))

2021-01-07 06:27 UTC, KirillKarpov commented on src/main/java/task3pageobject/TablePage.java
> +            String name=employee.findElement(By.xpath(".//td[1]")).getText();
Прям совсем не ошибка, но раз тебе возвращается строка, то не имеет смысла искать на всех уровнях вложенности  (.//), достаточно найти на следующем уровне вложенности (./)

2021-01-07 06:27 UTC, KirillKarpov commented on src/main/java/task3pageobject/TableTest.java
> +        assertTrue(select.isSelected());
Не до конца понимаю зачем этот код. По умолчанию на страницы выбирается 10 значений. Этот код кажется избыточным.

2021-01-07 06:27 UTC, KirillKarpov commented on src/main/java/task3pageobject/WaitForUserTest.java
> +        driver.findElement(By.xpath("//button[text()='Get New User']")).click();
как обычно :). Старайся избегать if. В особенности на уровне теста.
А что будет с твоим тестом если if не отработал ?

2021-01-07 06:27 UTC, KirillKarpov commented on src/main/java/task4/LoginLogoutTestPF.java
> +        MainPagePF mainPagePF=PageFactory.initElements(driver, MainPagePF.class);
Часть с инициализацией элементов лучше закидывать в конструктор класса (MainPagePF )

2021-01-07 06:27 UTC, KirillKarpov commented on src/main/java/task4/LoginLogoutTestPF.java
> +        loginPagePO.takeScreen(driver, "C:\\screenschot\\screen2.png");
класть лучше в папку target на уровне твоего проекта. Поэтому лучше делать относительный путь, вместо абсолютного

2021-01-07 06:27 UTC, KirillKarpov commented on src/main/java/task4/LoginPagePF.java
> +    @FindBy(xpath="//span[text()='Selenium Test']")
А если текст будет другой, то элемент не найдётся? Предположим у моего юзера имя Kirill Karpov

2021-01-07 06:27 UTC, KirillKarpov commented on src/main/java/task4/LoginPagePF.java
> +        }
Лучше создать отдельный класс (например Utils ) и положить метод туда. Сам метод не принадлежит это страницы и может быть использован на любой странице

2021-01-07 06:27 UTC, KirillKarpov commented on src/main/java/task4/MainPagePF.java
> +        if (!logoutButton.isSelected())
зачем if тут ?

2021-01-07 06:27 UTC, KirillKarpov commented on src/main/java/task4/MainPagePO.java
> +        WebElement logoutButton=driver.findElement(By.xpath("//a[text()='Выйти']"));
зачем объявлять WebElement тут, а не на строчке 17 например?

2021-01-07 06:27 UTC, KirillKarpov commented on src/main/java/task4/MainPagePO.java
> +        if (!logoutButton.isSelected()) {
зачем if ?

2021-01-07 06:27 UTC, KirillKarpov commented on src/main/java/task4/MainPagePO.java
> +        this.clickUserLink();
к методы на этой странице можно обращаться и без ключевого слова this. Это избыточное обращение

2021-01-07 06:27 UTC, KirillKarpov commented on src/main/java/task4/LoginPagePF.java
> +    public static void takeScreen(WebDriver webdriver, String fileWithScreen) {
fileWithScreen лучше назвать filePath. В идеала вообще стоит убрать эту переменную из метода и сделать так чтобы путь и имя файла генерировались на  уровне метода.

2021-01-09 19:08 UTC, Mash-Masha commented on src/main/java/LoginLogoutTest.java
> +        WebElement button=driver.findElement(By.xpath("//div[@class='b-hold']//input[@value='Войти']"));
сделано

2021-01-09 19:08 UTC, Mash-Masha commented on src/main/java/task3pageobject/AlertMainPage.java
> +    }
сделано

2021-01-09 19:09 UTC, Mash-Masha commented on src/main/java/task3pageobject/AlertMainPage.java
> +    private By button2=By.xpath("//button[@onclick='myPromptFunction()']");
Помню при разговоре с тобой,исправила в некоторых моментах,где было,а здесь не заметила и забыла.Впредь,когда буду писать код буду знать

2021-01-09 19:10 UTC, Mash-Masha commented on src/main/java/task3pageobject/AlertTest.java
> +        System.setProperty("webdriver.chrome.driver", "C:\\javalessons\\driver\\chromedriver.exe");
тоже везде исправила,про слеш было для меня новой и очень полезной информацией.Спасибо

2021-01-09 19:11 UTC, Mash-Masha commented on src/main/java/task4/MainPagePF.java
> +        if (!logoutButton.isSelected())
я как проверку эту записала,думала так правильнее писать.Исправила

2021-01-09 19:11 UTC, Mash-Masha commented on src/main/java/task4/MainPagePO.java
> +        WebElement logoutButton=driver.findElement(By.xpath("//a[text()='Выйти']"));
исправила этот момент тоже

2021-01-09 19:12 UTC, Mash-Masha commented on src/main/java/task4/MainPagePO.java
> +        if (!logoutButton.isSelected()) {
)))испраавила

2021-01-09 19:13 UTC, Mash-Masha commented on src/main/java/task4/MainPagePO.java
> +        this.clickUserLink();
Никогда не видела,чтобы обращения писались без this.Теперь буду знать,то и так можно.Все время думала что только через this

2021-01-09 19:13 UTC, Mash-Masha commented on src/main/java/task4/MainPagePO.java
> +        this.clickUserLink();
исправила

2021-01-09 19:14 UTC, Mash-Masha commented on src/main/java/task4/LoginPagePF.java
> +    public static void takeScreen(WebDriver webdriver, String fileWithScreen) {
Сделала,надеюсь сделала все правильно,проверила,код работает

2021-01-09 19:32 UTC, Mash-Masha commented on src/main/java/task3pageobject/MultiSelectTest2.java
> +    }
он записан у меня в классе MultiSelectTest и я здесь просто т.к.работала с Action и у меня по какой-то причине не выбирается еще один и  я,к сожалению,не понимаю почему так,поэтому и оставила чтобы ты посмотрел и исправил

2021-01-09 19:35 UTC, Mash-Masha commented on src/main/java/task3pageobject/TablePage.java
> +        allRows.remove(0);
да,можно и так,согласна с тобой,когда писала видела что таблицу можно выбрать так и так.и соответсвенно написала вот так и еще думала как правильнее написать и в итоге оставила так

2021-01-10 02:15 UTC, Mash-Masha commented on src/main/java/task3pageobject/AlertTest.java
> +            WebElement message=driver.findElement(By.xpath("//p[@id='confirm-demo']"));
сделано

2021-01-10 02:17 UTC, Mash-Masha commented on src/main/java/task3pageobject/AlertTest.java
> +            Thread.sleep(3000);
один тест второй написала без статического ожидания

2021-01-10 02:18 UTC, Mash-Masha commented on src/main/java/task3pageobject/LoginTest.java
> +        System.setProperty("webdriver.chrome.driver", "C:\\javalessons\\driver\\chromedriver.exe");
исправила

2021-01-10 02:19 UTC, Mash-Masha commented on src/main/java/task3pageobject/MainPage.java
> +    }
сделано

2021-01-10 02:20 UTC, Mash-Masha commented on src/main/java/task3pageobject/MainPage.java
> +
сделано

2021-01-10 02:36 UTC, Mash-Masha commented on src/main/java/task3pageobject/MultiSelectTest.java
> +            isSelectCalifornia.click();
сделано

2021-01-10 02:36 UTC, Mash-Masha commented on src/main/java/task3pageobject/MultiSelectTest.java
> +        WebElement isSelectCalifornia=driver.findElement(By.xpath("//option[text()='California']"));
сделано

2021-01-10 02:37 UTC, Mash-Masha commented on src/main/java/task3pageobject/MultiSelectTest.java
> +    public void isSelectedRows() {
сделано

2021-01-10 02:44 UTC, Mash-Masha commented on src/main/java/task3pageobject/SignInPage.java
> +
да,все верно,так оно и было,просто я чутка позже это заметила,когда уже на 4 таске была,и здесь не исправила

2021-01-10 02:45 UTC, Mash-Masha commented on src/main/java/task3pageobject/TablePage.java
> +
убраны

2021-01-10 02:46 UTC, Mash-Masha commented on src/main/java/task3pageobject/TablePage.java
> +            String salary1=employee.findElement(By.xpath(".//td[6]")).getText();
сделано

2021-01-10 02:47 UTC, Mash-Masha commented on src/main/java/task3pageobject/TablePage.java
> +        allRows.remove(0);
сделано

2021-01-10 02:47 UTC, Mash-Masha commented on src/main/java/task3pageobject/TablePage.java
> +            String name=employee.findElement(By.xpath(".//td[1]")).getText();
согласна,исправила

2021-01-10 02:49 UTC, Mash-Masha commented on src/main/java/task3pageobject/TableTest.java
> +        assertTrue(select.isSelected());
исправила

2021-01-10 02:54 UTC, Mash-Masha commented on src/main/java/task3pageobject/WaitForUserTest.java
> +        driver.findElement(By.xpath("//button[text()='Get New User']")).click();
я понеяла,усвоила этот урок,больше не использую)

исправила

2021-01-10 09:04 UTC, Mash-Masha commented on src/main/java/task3pageobject/AlertMainPage.java
> +    private By button2=By.xpath("//button[@onclick='myPromptFunction()']");
done

2021-01-10 09:50 UTC, Mash-Masha commented on src/main/java/task3pageobject/LoginTest.java
> +        wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//span[text()='Selenium Test']")));
проверки добавила,все что надо было из теста спрятала в MainPage

2021-01-10 09:53 UTC, Mash-Masha commented on src/main/java/task3pageobject/MainPage.java
> +    public SignInPage loginWithInvalidCreds(String login, String password) {
done

2021-01-10 12:16 UTC, Mash-Masha commented on src/main/java/task4/LoginPagePF.java
> +    @FindBy(xpath="//span[text()='Selenium Test']")
исправила

2021-01-10 13:00 UTC, Mash-Masha commented on src/main/java/task4/LoginPagePF.java
> +        }
done

2021-01-10 13:11 UTC, Mash-Masha commented on src/main/java/task3pageobject/MainPageTest.java
> +    }
сделано

2021-01-10 17:20 UTC, Mash-Masha commented on src/main/java/LoginLogoutTest.java
> +        driver.findElement(By.xpath("//div[@class='b-hold']/input[2]")).sendKeys("123456789zxcvbn");
done

2021-01-10 17:21 UTC, Mash-Masha commented on src/main/java/task3pageobject/RefreshTest.java
> +            actions.sendKeys(Keys.F5).build().perform();
done

2021-01-10 17:21 UTC, Mash-Masha commented on src/main/java/task3pageobject/SignInPage.java
> +
done

2021-01-10 17:22 UTC, Mash-Masha commented on src/main/java/task4/LoginLogoutTestPF.java
> +        loginPagePO.takeScreen(driver, "C:\\screenschot\\screen2.png");
done

2021-01-10 17:23 UTC, Mash-Masha commented on src/main/java/task4/LoginLogoutTestPF.java
> +        loginPagePO.takeScreen(driver, "C:\\screenschot\\screen2.png");
я поменяла путь,но не в папке таргет он у меня лежит,надо мне изменить на папку таргет?

2021-01-10 17:24 UTC, Mash-Masha commented on src/main/java/task4/LoginPagePF.java
> +    @FindBy(xpath="//span[text()='Selenium Test']")
только поменяла путь,но не создала папку таргет,т.к.первоначально ее у меня не было.Создать и поместить туда?

2021-01-10 17:41 UTC, Mash-Masha commented on src/main/java/task4/LoginLogoutTestPF.java
> +        MainPagePF mainPagePF=PageFactory.initElements(driver, MainPagePF.class);
done

2021-01-11 11:14 UTC, kirylKarpau requested changes

2021-01-11 11:14 UTC, kirylKarpau commented on src/main/java/task3pageobject/AlertPage.java
> +        assertEquals(alertMainPage.getMessage(), "You pressed OK!");
ассерт надо вернуть на уровень тестового класса.
считается плохим тоном ассертать на уровне страницы

2021-01-11 11:14 UTC, kirylKarpau commented on src/main/java/task3pageobject/MainPage.java
> +    }
нету большого смысла создавать отдельный метод. Можно проверку на наличие вебэлемента expectedText добавить в метод loginWithCreds() перед return

2021-01-11 11:14 UTC, kirylKarpau commented on src/main/java/task3pageobject/MultiSelectTest2.java
> +    }
не увидел проблем. У меня выделяет первую строку(Калифорния). Переделай тогда MultiSelectTest на работу с select классом. Сейчас там ты работаешь с WebElement

2021-01-11 11:14 UTC, kirylKarpau commented on src/main/java/task3pageobject/WaitForUserTest.java
> +        WebDriverWait waitUser=(new WebDriverWait(driver,10));
правильней называть эту переменную просто wait

2021-01-11 11:14 UTC, kirylKarpau commented on src/main/java/task4/LoginPagePF.java
> +        PageFactory.initElements(driver, this);
не вижу инициализации самого драйвера. 
this.driver= driver;
Видимо он тебе в этом классе не понадобился

2021-01-11 11:14 UTC, kirylKarpau commented on src/main/java/task4/LoginPagePF.java
> +    }
1) this
2) имя метода

2021-01-11 11:14 UTC, kirylKarpau commented on src/main/java/task4/LoginPagePO.java
> +        driver.findElement(emailField).sendKeys("seleniumtests@tut.by");
плохое правило харкодить какие-то значения в метод. В твоём случае seleniumtests@tut.by

2021-01-11 11:14 UTC, kirylKarpau commented on src/main/java/task4/LoginPagePO.java
> +        driver.findElement(passwordField).sendKeys("123456789zxcvbn");
плохое правило харкодить какие-то значения в метод

2021-01-11 11:14 UTC, kirylKarpau commented on src/main/java/task4/Utils.java
> +    }
Утилитарные классы обычно без конструктора идут, потому что все методы в них статические.
Плюс ты сама нигде не используешь этот драйвер

2021-01-11 11:14 UTC, kirylKarpau commented on src/main/java/task4/Utils.java
> +    public static void takeScreen(WebDriver webdriver, String filePath) {
Избавься от второго параметра 'String filePath'. Совсем нет необходимости говорить на уровне теста куда сохранять файл.
Имя файла можно генерировать на лету. Например,  String fileName = new Date().toString().replace(":", "_").replace(" ", "_") + ".png";

2021-01-11 11:14 UTC, kirylKarpau commented on src/main/java/task4/Utils.java
> +            FileUtils.copyFile(screenFile, destFile);
Лучше использовать moveFile вместо copyFile. 
C использованием fileName, это будет выглядить примерно так
  FileUtils.moveFile(screenshot, new File("./screenshots/" + fileName));

2021-01-16 16:01 UTC, Mash-Masha commented on src/main/java/task4/LoginPagePF.java
> +        PageFactory.initElements(driver, this);
использую,почему-то он удалился здесь случайно.исправила

2021-01-16 16:01 UTC, Mash-Masha commented on src/main/java/task4/Utils.java
> +    }
да,все верно,его я здесь нигде не использую.машинально сразу написала и даже не посмотрела,когда создавла класс,потому что через копи паст.справила

2021-01-16 16:01 UTC, Mash-Masha commented on src/main/java/task4/Utils.java
> +    public static void takeScreen(WebDriver webdriver, String filePath) {
исправила

2021-01-16 16:01 UTC, Mash-Masha commented on src/main/java/task4/Utils.java
> +            FileUtils.copyFile(screenFile, destFile);
Хотела уже писать,как сделать,чтобы доп в папку закидывать в которую создала,т.к.он просто этот скрин в общую папку закидывал,,а ты здесь уже написал)исправила)

2021-01-16 16:01 UTC, Mash-Masha commented on src/main/java/task3pageobject/WaitForUserTest.java
> +        WebDriverWait waitUser=(new WebDriverWait(driver,10));
исправила на waitForUser,т.к.wait возникает ошибка

2021-01-16 16:01 UTC, Mash-Masha commented on src/main/java/task3pageobject/MainPage.java
> +    }
ок,поняла,исправила

2021-01-16 16:01 UTC, Mash-Masha commented on src/main/java/task3pageobject/AlertPage.java
> +        assertEquals(alertMainPage.getMessage(), "You pressed OK!");
испраивла

2021-01-16 16:02 UTC, merged